Animais Carentes/Controllers/AgendamentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Animais_Carentes.Models;

namespace Animais_Carentes.Controllers
{
    public class AgendamentoController : Controller
    {
        private contexto db = new contexto();

        // GET: Agendamento
        public ActionResult Index()
        {
            return View(db.AgendamentoModels.ToList());
        }

        // GET: Agendamento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgendamentoModel agendamentoModel = db.AgendamentoModels.Find(id);
            if (agendamentoModel == null)
            {
                return HttpNotFound();
            }
            return View(agendamentoModel);
        }

        // GET: Agendamento/Create/5
        public ActionResult Create(string cnpj)
        {
            if (cnpj == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AgendamentoModel model = new AgendamentoModel();
            model.ong = db.OngModels.First(a => a.cnpj == cnpj);
            return View(model);
        }

        // POST: Agendamento/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,dataEntrega,usuarioEntrega,enderecoEntrega,animal")] AgendamentoModel agendamentoModel, string cnpj)
        {
            agendamentoModel.ong = db.OngModels.First(a => a.cnpj == cnpj);
            agendamentoModel.usuario = db.UsuarioModels.First();
            if (ModelState.IsValid)
            {  
                db.AgendamentoModels.Add(agendamentoModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agendamentoModel);
        }

        // GET: Agendamento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgendamentoModel agendamentoModel = db.AgendamentoModels.Find(id);
            if (agendamentoModel == null)
            {
                return HttpNotFound();
            }
            return View(agendamentoModel);
        }

        // POST: Agendamento/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,dataEntrega,usuarioEntrega,enderecoEntrega,animal")] AgendamentoModel agendamentoModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agendamentoModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agendamentoModel);
        }

        // GET: Agendamento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgendamentoModel agendamentoModel = db.AgendamentoModels.Find(id);
            if (agendamentoModel == null)
            {
                return HttpNotFound();
            }
            return View(agendamentoModel);
        }

        // POST: Agendamento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgendamentoModel agendamentoModel = db.AgendamentoModels.Find(id);
            db.AgendamentoModels.Remove(agendamentoModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Animais Carentes/Controllers/OngController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Animais_Carentes.Models;

namespace Animais_Carentes.Controllers
{
    public class OngController : Controller
    {
        private contexto db = new contexto();

        // GET: Ong
        public ActionResult Index()
        {
            return View(db.OngModels.ToList());
        }

        // GET: Ong/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OngModel ongModel = db.OngModels.Find(id);
            if (ongModel == null)
            {
                return HttpNotFound();
            }
            return View(ongModel);
        }

        // GET: Ong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ong/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cnpj,nome,cep,estado,cidade,bairro,rua,numero,telefone,email,senha")] OngModel ongModel)
        {
            if (ModelState.IsValid)
            {
                db.OngModels.Add(ongModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ongModel);
        }

        // GET: Ong/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OngModel ongModel = db.OngModels.Find(id);
            if (ongModel == null)
            {
                return HttpNotFound();
            }
            return View(ongModel);
        }

        // POST: Ong/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cnpj,nome,cep,estado,cidade,bairro,rua,numero,telefone,email,senha")] OngModel ongModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ongModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ongModel);
        }

        // GET: Ong/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OngModel ongModel = db.OngModels.Find(id);
            if (ongModel == null)
            {
                return HttpNotFound();
            }
            return View(ongModel);
        }

        // POST: Ong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            OngModel ongModel = db.OngModels.Find(id);
            db.OngModels.Remove(ongModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Animais Carentes/Views/Ong/Create.cshtml
@model Animais_Carentes.Models.OngModel

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Criar Ong</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-3 "></div>
        <div class="col-md-3 ">
            @Html.LabelFor(model => model.cnpj, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cnpj, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cnpj, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3 "></div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.cep, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cep, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cep, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3 "></div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.cidade, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.bairro, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.bairro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.bairro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3 "></div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.rua, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.rua, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rua, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3 "></div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefone, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3 "></div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.senha, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-offset-2">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Animais Carentes/Views/Ong/Delete.cshtml
@model Animais_Carentes.Models.OngModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OngModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senha)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Animais Carentes/Views/Ong/Details.cshtml
@model Animais_Carentes.Models.OngModel

@{
    ViewBag.Title = "Details";
}

<h2 class="text-center">@Model.nome</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senha)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.cnpj }) |
    @Html.ActionLink("Agendar", "Create", "Agendamento", new { cnpj = Model.cnpj }, null) |
    @Html.ActionLink("Back to List", "Index")
</p>

Animais Carentes/Views/Ong/Edit.cshtml
@model Animais_Carentes.Models.OngModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OngModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.cnpj)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Animais Carentes/Views/Ong/Index.cshtml
@model IEnumerable<Animais_Carentes.Models.OngModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cep)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bairro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rua)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.senha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cep)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bairro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rua)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.numero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.senha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.cnpj }) |
            @Html.ActionLink("Details", "Details", new { id=item.cnpj }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.cnpj })
        </td>
    </tr>
}

</table>