Animais Carentes/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Animais_Carentes.Models;

namespace Animais_Carentes.Controllers
{
    public class AnimalController : Controller
    {
        private contexto db = new contexto();

        // GET: Animal
        public ActionResult Index()
        {
            return View(db.AnimalModels.ToList());
        }

        // GET: Animal/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnimalModel animalModel = db.AnimalModels.Find(id);
            if (animalModel == null)
            {
                return HttpNotFound();
            }
            return View(animalModel);
        }

        // GET: Animal/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Animal/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,especie,raca,descricao")] AnimalModel animalModel)
        {
            if (ModelState.IsValid)
            {
                db.AnimalModels.Add(animalModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(animalModel);
        }

        // GET: Animal/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnimalModel animalModel = db.AnimalModels.Find(id);
            if (animalModel == null)
            {
                return HttpNotFound();
            }
            return View(animalModel);
        }

        // POST: Animal/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,especie,raca,descricao")] AnimalModel animalModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(animalModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(animalModel);
        }

        // GET: Animal/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnimalModel animalModel = db.AnimalModels.Find(id);
            if (animalModel == null)
            {
                return HttpNotFound();
            }
            return View(animalModel);
        }

        // POST: Animal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AnimalModel animalModel = db.AnimalModels.Find(id);
            db.AnimalModels.Remove(animalModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Animais Carentes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Animais Carentes</title>
    <link href="~/Content/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    <!--slider-->
    <link href="css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Content/web/js/jquery-1.9.0.min.js"></script>
    <script type="text/javascript" src="~/Content/web/js/jquery.nivo.slider.js"></script>
    <script type="text/javascript">
        $(window).load(function () {
            $('#slider').nivoSlider();
        });
    </script>
    <!--light-box-->
    <script type="text/javascript" src="~/Content/web//js/jquery.lightbox.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/web/css/lightbox.css" media="screen">
    <script type="text/javascript">
        $(function () {
            $('.gallery a').lightBox();
        });
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrap">
        <div class="header-top">
            <div class="logo">
                <a href="index.html"><img src="~/Content/web/images/logo.png" alt="" /></a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="header-bottom">
        <div class="wrap">
            <div id="cssmenu">
                <ul>
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("ONG", "Index", "ONG")</li>
                    <li>@Html.ActionLink("Exposição de animais", "Index", "Animal")</li>
                    <li>@Html.ActionLink("Usuario", "Index", "Usuario")</li>
                    <li class="last">@Html.ActionLink("Sobre", "About", "Home")</li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    @RenderBody()
    <div class="footer">
        <div class="wrap">
            <div class="copy">
                <p> © 2013 All rights Reserved | Design by <a href="http://w3layouts.com">W3Layouts</a></p>
            </div>
            <ul class="follow_icon">
                <li><a href="#" style="opacity: 1;"><img src="images/fb.png" alt=""></a></li>
                <li><a href="#" style="opacity: 1;"><img src="images/tw.png" alt=""></a></li>
                <li><a href="#" style="opacity: 1;"><img src="images/rss.png" alt=""></a></li>
                <li><a href="#" style="opacity: 1;"><img src="images/g+.png" alt=""></a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="footer-bot">
            <a href="#toTop" class="toTop">&uarr;</a>
            <script type="text/javascript">
                $('.toTop ').click(function () {
                    $("html, body").animate({ scrollTop: 0 }, 600);
                    return false;
                });
                $('.toBottom').click(function () {
                    $('html,body').animate({ scrollTop: $(document).height() }, 600);
                    return false;
                });
            </script>
        </div>
        <div class="clear"></div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>